"""
Dynamic Attack Catalog (Red Team Engine).
Generates fraud data with randomized parameters each epoch.
"""

import logging
import random
import uuid
import pickle
from typing import Dict, Any, List, Tuple

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker('en_IN')
logger = logging.getLogger(__name__)

# =====================================================================
# 1. CTGAN POST-PROCESSING (For Legitimate Traffic Generation)
# =====================================================================

def post_process_ctgan_output(synthetic_df: pd.DataFrame) -> pd.DataFrame:
    """Clamp impossible values generated by CTGAN."""
    df = synthetic_df.copy()
    df['amount'] = df['amount'].clip(lower=50)                    
    df['dwell_time_seconds'] = df['dwell_time_seconds'].clip(lower=10)  
    df['hour_of_day'] = df['hour_of_day'].clip(0, 23).round().astype(int)
    df['day_of_week'] = df['day_of_week'].clip(0, 6).round().astype(int)
    df['is_structured'] = df['is_structured'].round().clip(0, 1).astype(int)
    return df

def generate_legit_from_ctgan(ctgan_model_path: str, n_samples: int = 5000) -> pd.DataFrame:
    """Load trained CTGAN_LEGIT and generate post-processed legitimate transactions. Fallback to mock if not found."""
    try:
        import torch
        import io
        # Monkey-patch torch.load to force CPU mapping for CUDA-trained models
        _original_torch_load = torch.load
        def _cpu_torch_load(*args, **kwargs):
            kwargs['map_location'] = torch.device('cpu')
            return _original_torch_load(*args, **kwargs)
        torch.load = _cpu_torch_load
        try:
            with open(ctgan_model_path, 'rb') as f:
                ctgan = pickle.load(f)
        finally:
            torch.load = _original_torch_load  # Always restore
        synthetic = ctgan.sample(n_samples)
        synthetic = post_process_ctgan_output(synthetic)
        return synthetic
    except Exception as e:
        logger.warning(f"⚠️ Could not load CTGAN model ({e}). Generating mock legitimate transactions instead.")
        # Generate realistic mock data
        amounts = np.random.lognormal(mean=7.0, sigma=1.2, size=n_samples) # log-normal amounts
        amounts = np.clip(amounts, 50, 50000) # clamp
        
        # dwell times: most are long, some fast
        dwell_times = np.random.exponential(scale=3600, size=n_samples) + 10
        dwell_times = np.clip(dwell_times, 10, 86400)
        
        rails = np.random.choice(['BANK', 'UPI', 'WALLET'], size=n_samples, p=[0.2, 0.6, 0.2])
        is_structured = np.zeros(n_samples, dtype=int)
        # structured if ₹8500-₹10000
        for idx in range(n_samples):
            if 8500 <= amounts[idx] <= 10000:
                is_structured[idx] = 1 if np.random.rand() < 0.1 else 0
                
        df = pd.DataFrame({
            'amount': np.round(amounts, 2),
            'rail': rails,
            'dwell_time_seconds': dwell_times.astype(int),
            'is_structured': is_structured
        })
        return df

# =====================================================================
# 2. DYNAMIC ATTACK CATALOG (Core Red Team Engine)
# =====================================================================

class DynamicAttackCatalog:
    """Generates fraud topologies whose parameters adapt to the Blue Team's blind spots."""
    TOPOLOGY_TYPES = ['fan_out_fan_in', 'cross_rail', 'circular', 'star_burst']
    
    def __init__(self, accounts_path: str = 'data/seed_accounts_nodes.csv'):
        self.base_accounts_df = pd.read_csv(accounts_path)
        self.accounts_df = self.base_accounts_df.copy()
        self._refresh_lookups()
    
    def _refresh_lookups(self):
        """Rebuild account lookups after the population changes."""
        self.mule_accs = self.accounts_df[self.accounts_df['is_mule'] == 1]['account_id'].tolist()
        self.normal_accs = self.accounts_df[self.accounts_df['is_mule'] == 0]['account_id'].tolist()
        self.account_lookup = self.accounts_df.set_index('account_id').to_dict(orient='index')
    
    def generate_epoch_accounts(self, params: Dict[str, Any]) -> pd.DataFrame:
        """Create this epoch's account population."""
        n_normal = 200
        n_mules = 50
        accounts = []
        
        mule_age_range = params.get('mule_age_range', (15, 90))
        device_share_ratio = params.get('device_sharing_ratio', 0.3)
        
        n_legit_sharing_groups = random.randint(10, 30)
        legit_shared_devices = [f"DEV_FAM_{str(uuid.uuid4())[:6]}" for _ in range(n_legit_sharing_groups)]
        legit_shared_ips = [f"192.168.{random.randint(1, 50)}.0/24" for _ in range(n_legit_sharing_groups)]
        
        for i in range(n_normal):
            legit_share_chance = random.uniform(0.20, 0.40)
            if random.random() < legit_share_chance:
                group = i % n_legit_sharing_groups
                device = legit_shared_devices[group]
                ip = legit_shared_ips[group]
            else:
                device = f"DEV_L_{str(uuid.uuid4())[:8]}"
                ip = f"192.168.{random.randint(1, 255)}.0/24"
            
            accounts.append({
                'account_id': str(uuid.uuid4())[:8],
                'account_type': random.choice(['SAVINGS', 'CURRENT', 'WALLET']),
                'account_age_days': random.randint(30, 3000),
                'kyc_status': 'FULL',
                'device_hash': device,
                'ip_subnet': ip,
                'is_mule': 0
            })
        
        n_clusters = max(1, n_mules // 5)
        n_shared_device_mules = int(n_mules * device_share_ratio)
        
        shared_devices = [f"DEV_M_{str(uuid.uuid4())[:6]}" for _ in range(n_clusters)]
        shared_ips = [f"10.0.{random.randint(1, 10)}.0/24" for _ in range(n_clusters)]
        
        for i in range(n_mules):
            cluster_idx = i % n_clusters
            age = random.randint(mule_age_range[0], mule_age_range[1])
            
            if i < n_shared_device_mules:
                device = shared_devices[cluster_idx]
                ip = shared_ips[cluster_idx]
            else:
                device = f"DEV_U_{str(uuid.uuid4())[:8]}"
                ip = f"172.16.{random.randint(1, 255)}.0/24"
            
            accounts.append({
                'account_id': str(uuid.uuid4())[:8],
                'account_type': random.choice(['SAVINGS', 'WALLET', 'CRYPTO', 'CURRENT']),
                'account_age_days': age,
                'kyc_status': random.choice(['MIN', 'NONE', 'FULL', 'FULL']),
                'device_hash': device,
                'ip_subnet': ip,
                'is_mule': 1
            })
        
        self.accounts_df = pd.DataFrame(accounts)
        self._refresh_lookups()
        
        shared_pct = n_shared_device_mules / n_mules * 100
        logger.info(f"  🔄 Fresh accounts generated: {n_normal} legit, {n_mules} mules")
        logger.info(f"     Mule age range: {mule_age_range}")
        logger.info(f"     Mule device sharing: {shared_pct:.0f}% shared, {100-shared_pct:.0f}% unique")
        logger.info(f"     Legit device sharing: ~30% (family/roommate groups)")
        
        return self.accounts_df
    
    def generate_epoch_params(self, epoch: int = 0, blind_spots: Dict[str, Any] = None) -> Dict[str, Any]:
        """Pick this epoch's attack parameters, shifted by any blind spots found."""
        params = {
            'amount_mean': random.uniform(3000, 20000),
            'amount_std_ratio': random.uniform(0.05, 0.30),
            'topology': random.sample(
                self.TOPOLOGY_TYPES, 
                k=min(random.randint(2, 3), len(self.TOPOLOGY_TYPES))
            ),
            'fan_out_degree': random.randint(2, 8),
            'num_hops': random.randint(1, 4),
            'dwell_time_min': random.randint(15, 300),
            'dwell_time_max': random.randint(300, 3600),
            'chain_spread_hours': random.uniform(0.5, 48),
            'device_sharing_ratio': random.uniform(0.05, 0.5),
            'noise_txn_per_mule': random.randint(1, 5),
            'noise_amount_range': (50, random.uniform(500, 2000)),
            'n_networks': random.randint(5, 20),
            'mules_per_network': random.randint(3, 7),
            'mule_age_range': random.choice([
                (15, 90),     
                (180, 500),   
                (30, 365),    
            ]),
        }
        
        if blind_spots:
            params = self._apply_blind_spots(params, blind_spots)
            topology_weakness = blind_spots.get('topology_weakness', {})
            if topology_weakness:
                import math
                tau = 0.5  
                scores = []
                for t in self.TOPOLOGY_TYPES:
                    f1 = topology_weakness.get(t, 0.5) 
                    scores.append(math.exp((1.0 - f1) / tau))
                total = sum(scores)
                weights = [s / total for s in scores]
                
                k = min(random.randint(2, 3), len(self.TOPOLOGY_TYPES))
                params['topology'] = list(np.random.choice(
                    self.TOPOLOGY_TYPES, size=k, replace=False, p=weights
                ))
                logger.info(f"     Topology weights (softmax τ={tau}):")
                for t, w in zip(self.TOPOLOGY_TYPES, weights):
                    f1 = topology_weakness.get(t, 0.5)
                    logger.info(f"       {t:<20} F1={f1:.2f} → weight={w:.3f}")
        
        return params
    
    def _apply_blind_spots(self, params: Dict[str, Any], blind_spots: Dict[str, Any]) -> Dict[str, Any]:
        """Bias parameters toward whatever the detector has been missing."""
        for param_name, info in blind_spots.items():
            if param_name in params and isinstance(params[param_name], (int, float)):
                shift = info.get('shift', 0) * 0.7
                new_val = params[param_name] + shift
                
                if isinstance(params[param_name], int):
                    params[param_name] = max(1, int(new_val))
                else:
                    params[param_name] = max(0.01, new_val)
        
        return params
    
    def generate_fraud_batch(self, params: Dict[str, Any]) -> pd.DataFrame:
        """Generate one epoch's fraudulent transactions across all patterns."""
        topologies = params['topology'] if isinstance(params['topology'], list) else [params['topology']]
        all_records = []
        networks_per_topo = max(1, params['n_networks'] // len(topologies))
        
        for topology in topologies:
            for _ in range(networks_per_topo):
                if topology == 'fan_out_fan_in':
                    records = self._gen_fan_out_fan_in(params)
                elif topology == 'cross_rail':
                    records = self._gen_cross_rail(params)
                elif topology == 'circular':
                    records = self._gen_circular(params)
                elif topology == 'star_burst':
                    records = self._gen_star_burst(params)
                else:
                    records = self._gen_fan_out_fan_in(params)
                
                all_records.extend(records)
        
        if not all_records:
            return pd.DataFrame()
        return pd.DataFrame(all_records)
    
    def _get_meta(self, account_id: str) -> Dict[str, Any]:
        """Metadata for an account."""
        return self.account_lookup.get(account_id, {})
    
    def _make_txn(self, sender: str, receiver: str, amount: float, rail: str, dwell: float, 
                  is_fraud: int = 1, shared_hash: str = None, device_override: str = None) -> Dict[str, Any]:
        """Build a single transaction record."""
        sender_meta = self._get_meta(sender)
        return {
            'txn_id': str(uuid.uuid4()),
            'timestamp': fake.date_time_between(start_date='-15d', end_date='now'),
            'sender': sender,
            'receiver': receiver,
            'amount': round(max(50, amount), 2),
            'rail': rail,
            'device_hash': device_override or sender_meta.get('device_hash', f'DEV_{uuid.uuid4().hex[:6]}'),
            'ip_subnet': sender_meta.get('ip_subnet', '10.0.0.0/24'),
            'dwell_time_seconds': max(10, int(dwell)),
            'is_structured': 1 if 8500 <= amount <= 10000 else 0,
            'shared_hash': shared_hash,
            'is_fraud': is_fraud
        }
    
    def _gen_fan_out_fan_in(self, params: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Distribute funds through mules, then reconsolidate."""
        records = []
        n_mules = min(params['mules_per_network'], len(self.mule_accs) - 1)
        if n_mules < 2: return records
        
        source = random.choice(self.normal_accs)
        aggregator = random.choice(self.mule_accs)
        distributors = random.sample([m for m in self.mule_accs if m != aggregator], k=n_mules)
        
        for mule in distributors:
            amt = params['amount_mean'] * (1 + random.uniform(-params['amount_std_ratio'], params['amount_std_ratio']))
            dwell = random.randint(params['dwell_time_min'], params['dwell_time_max'])
            records.append(self._make_txn(source, mule, amt, 'BANK', dwell))
            
            pass_amt = amt - random.uniform(50, 300)
            dwell2 = random.randint(params['dwell_time_min'], params['dwell_time_max'])
            records.append(self._make_txn(mule, aggregator, pass_amt, 
                                          random.choice(['BANK', 'UPI']), dwell2))
            
            for _ in range(params['noise_txn_per_mule']):
                noise_amt = random.uniform(*params['noise_amount_range'])
                noise_dwell = random.randint(3600, 86400)
                records.append(self._make_txn(
                    mule, random.choice(self.normal_accs), noise_amt,
                    random.choice(['UPI', 'WALLET']), noise_dwell, is_fraud=0
                ))
        return records
    
    def _gen_cross_rail(self, params: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Hop funds across payment rails to break the audit trail."""
        records = []
        rails = ['BANK', 'UPI', 'WALLET', 'CRYPTO']
        chain_hash = f"CORR_{uuid.uuid4().hex[:8]}"
        amount = params['amount_mean']
        current_sender = random.choice(self.mule_accs)
        
        for rail in rails:
            current_receiver = random.choice([m for m in self.mule_accs if m != current_sender])
            dwell_max = max(params['dwell_time_min'] + 1, min(params['dwell_time_max'], 120))
            dwell = random.randint(params['dwell_time_min'], dwell_max)
            records.append(self._make_txn(
                current_sender, current_receiver, amount, rail, dwell,
                shared_hash=chain_hash
            ))
            amount -= random.uniform(50, 200) 
            current_sender = current_receiver
        return records
    
    def _gen_circular(self, params: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Cycle funds back to origin through intermediaries, decaying each hop."""
        records = []
        n_nodes = min(params['mules_per_network'], len(self.mule_accs))
        if n_nodes < 3: return records
        
        cycle_nodes = random.sample(self.mule_accs, k=n_nodes)
        amount = params['amount_mean']
        for i in range(len(cycle_nodes)):
            sender = cycle_nodes[i]
            receiver = cycle_nodes[(i + 1) % len(cycle_nodes)]
            dwell = random.randint(params['dwell_time_min'], params['dwell_time_max'])
            records.append(self._make_txn(sender, receiver, amount,
                                          random.choice(['BANK', 'UPI', 'WALLET']), dwell))
            amount -= random.uniform(20, 100)
        return records
    
    def _gen_star_burst(self, params: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Fan a single source out to many recipients at once."""
        records = []
        source = random.choice(self.mule_accs)
        n_targets = min(params['fan_out_degree'], len(self.mule_accs) - 1)
        targets = random.sample([m for m in self.mule_accs if m != source], k=n_targets)
        for target in targets:
            amt = params['amount_mean'] * (1 + random.uniform(-0.1, 0.1))
            dwell = random.randint(params['dwell_time_min'], params['dwell_time_max'])
            records.append(self._make_txn(source, target, amt,
                                          random.choice(['BANK', 'UPI']), dwell))
        return records

def generate_epoch_data(catalog: DynamicAttackCatalog, ctgan_path: str, epoch: int, 
                        blind_spots: Dict[str, Any] = None, n_legit: int = 5000, 
                        llm_controller: Any = None) -> Tuple[pd.DataFrame, Dict[str, Any], pd.DataFrame]:
    """Generate a complete training dataset for one adversarial loop epoch."""
    params = catalog.generate_epoch_params(epoch=epoch, blind_spots=blind_spots)
    
    if llm_controller:
        llm_response = llm_controller.generate_strategy(epoch, blind_spots, params)
        logger.info(f"\n{llm_response['narrative']}\n")
        params.update(llm_response['overrides'])
        
    accounts_df = catalog.generate_epoch_accounts(params)
    legit_features = generate_legit_from_ctgan(ctgan_path, n_samples=n_legit)
    
    legit_records = []
    all_accs = catalog.normal_accs + catalog.mule_accs
    account_lookup = catalog.account_lookup
    
    n_accs = len(all_accs)
    raw_weights = np.random.zipf(a=1.8, size=n_accs).astype(float)
    raw_weights = np.clip(raw_weights, 1, n_accs * 0.1)
    sender_weights = raw_weights / raw_weights.sum()
    
    raw_weights_recv = np.random.zipf(a=1.8, size=n_accs).astype(float)
    raw_weights_recv = np.clip(raw_weights_recv, 1, n_accs * 0.1)
    receiver_weights = raw_weights_recv / raw_weights_recv.sum()
    
    for _, row in legit_features.iterrows():
        sender = np.random.choice(all_accs, p=sender_weights)
        receiver = np.random.choice(all_accs, p=receiver_weights)
        while receiver == sender:
            receiver = np.random.choice(all_accs, p=receiver_weights)
        
        sender_meta = account_lookup.get(sender, {})
        legit_records.append({
            'txn_id': str(uuid.uuid4()),
            'timestamp': fake.date_time_between(start_date='-30d', end_date='now'),
            'sender': sender,
            'receiver': receiver,
            'amount': row['amount'],
            'rail': row['rail'],
            'device_hash': sender_meta.get('device_hash', f'DEV_{uuid.uuid4().hex[:6]}'),
            'ip_subnet': sender_meta.get('ip_subnet', '192.168.1.0/24'),
            'dwell_time_seconds': row['dwell_time_seconds'],
            'is_structured': row['is_structured'],
            'shared_hash': None,
            'is_fraud': 0
        })
    
    legit_df = pd.DataFrame(legit_records)
    fraud_df = catalog.generate_fraud_batch(params)
    
    if len(fraud_df) > 0:
        combined_df = pd.concat([legit_df, fraud_df], ignore_index=True)
    else:
        combined_df = legit_df
    
    combined_df = combined_df.sample(frac=1, random_state=epoch).reset_index(drop=True)
    
    fraud_count = combined_df['is_fraud'].sum()
    total = len(combined_df)
    
    logger.info(f"  📦 Epoch {epoch} Dataset:")
    logger.info(f"     Total txns:  {total}")
    logger.info(f"     Legit:       {total - fraud_count}")
    logger.info(f"     Fraud:       {fraud_count} ({fraud_count/total*100:.2f}%)")
    logger.info(f"     Topology:    {params['topology']}")
    
    return combined_df, params, accounts_df
